FROM nginx:alpine

# Copy static frontend files
COPY html/ /usr/share/nginx/html

# Copy Nginx dev config (can include security headers)
COPY nginx.conf /etc/nginx/nginx.conf
COPY security-headers.conf /etc/nginx/security-headers.conf

# Expose port 80
EXPOSE 80

# Start Nginx in foreground
CMD ["nginx", "-g", "daemon off;"]
